In [69]:
# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# Lab 4 – Pivot Tables, Permutation Testing, and Missing Values

## DSC 80, Spring 2022

### Due Date: Monday, April 25th at 11:59 PM

## Instructions
Much like in DSC 10, this Jupyter Notebook contains the statements of the problems and provides code and Markdown cells to display your answers to the problems. Unlike DSC 10, the notebook is *only* for displaying a readable version of your final answers. The coding will be done in an accompanying `lab.py` file that is imported into the current notebook.

Labs and programming assignments will be graded in (at most) two ways:
1. The functions and classes in the accompanying `lab.py` file will be tested (a la DSC 20),
2. The notebook may be graded (if it contains free response questions or asks you to draw plots).

<span style='color:red'><b>Note: For Lab 4 only, there are no hidden tests!</b></span> The tests you see when you run `grader.check` are the final tests that will determine your grade. In addition, when you submit Lab 4 to Gradescope you will see your final score on the assignment right away. (This is because the lab is due very close to the Midterm Exam.)

**Do not change the function names in the `*lab.py` file!**
- The functions in the `lab.py` file are how your assignment is graded, and they are graded by their name.
- If you changed something you weren't supposed to, just use git to revert! Ask us if you need help with this, or google around for `git revert`.

**Tips for working in the notebook**:
- The notebooks serve to present the questions and give you a place to present your results for later review.
- The notebooks in *lab assignments* are not graded (only the `lab.py` file is submitted and graded).
- The notebook serves as a nice environment for 'pre-development' and experimentation before designing your function in your `lab.py` file. You can write code here, but make sure that all of your real work is in the `lab.py` file.

**Tips for developing in the `lab.py` file**:
- Do not change the function names in the starter code; grading is done using these function names.
- Do not change the docstrings in the functions. These are there to tell you if your work is on the right track!
- You are encouraged to write your own additional helper functions to solve the lab! 
- Always document your code!

### Importing code from `lab.py`

* We import our `lab.py` file that's contained in the same directory as this notebook.
* We use the `autoreload` notebook extension to make changes to our `lab.py` file immediately available in our notebook. Without this extension, we would need to restart the notebook kernel to see any changes to `lab.py` in the notebook.
    - `autoreload` is necessary because, upon import, `lab.py` is compiled to bytecode (in the directory `__pycache__`). Subsequent imports of `lab` merely import the existing compiled python.

In [70]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [71]:
from lab import *

In [72]:
import pandas as pd
import numpy as np
import io
import os
from datetime import time

<span style='color:red'><b>New: Check <a href=https://campuswire.com/c/G325FA25B/feed/754>this</a> Campuswire post for any clarifications each time you start working on the lab.</b></span>

### Question 0 – Mid-Quarter Survey 🙋

Course staff, along with the Data Science Student Representatives, have put together a mid-quarter survey that will allow you to share feedback on your experience in DSC 80 so far. It is **entirely anonymous**, so we encourage you to be honest.

<br>

<center><b><a href=https://docs.google.com/forms/d/e/1FAIpQLSd9k90fGqPKDRAnHjFBEx5kak_VtvYN5Fq5uPv9jyqrryaKeA/viewform>Click here to access the mid-quarter survey.</a></b></center>

<br>

We'd like to have as many students as possible in the class fill out the survey. **As such, if 80% of the class fills out this survey before the Midterm Exam, then everyone will earn an extra point on the Midterm Exam.** The survey will close before the Midterm Exam. 

We really appreciate your feedback, thanks! 😊

## Part 1: Time Series Data

Imagine that you own an online store and you'd like to monitor the visits to your site. You've collected some data that you store in `data/login_table.csv`. It contains the information about different login dates and times for different users. Some users are unique, some visited your store multiple times.

You need to answer a few questions below in order to understand the login patters of your users.

### Question 1 – Passwords 🔑

Write a function `latest_login` which takes in a DataFrame like `login` and outputs a DataFrame indexed by `'Login Id'`, of the login that occurs at the latest time-of-day for each user. Latest time-of-day is as it says: the latest time, **regardless of how recent the day is**. The DataFrame should have just one column, named `'Time'`.

For example, if a user always logs in once per day at noon, but her most recent log in happened to be at 8:00PM, then her latest log-in time becomes 8:00PM. Note that the values in your returned DataFrame should only include times, not dates.

***Note:*** You do not need to use Python's `datetime` module – instead, use the built-in `pandas` methods for working with times that we introduced in [Lecture 9](https://dsc80.com/resources/lectures/lec09/lec09.html) (though you will need to do a bit more research to fully answer the question). Do not use a `for`-loop.

In [42]:
def cool():return 0

In [ ]:
def clean_time

In [43]:

login['Time'] = pd.to_datetime(login['Time'])
login['times']  = login['Time'].apply(extract_time)
login = login.drop(columns = 'Time')
login = login.groupby('Login Id').max()
login.dtypes

ValueError: Could not convert object to NumPy datetime

In [125]:
fp = os.path.join('data', 'login_table.csv')
login = pd.read_csv(fp)
login#.dtypes

Login Id                 Time
0          466  2017-01-07 18:24:07
1          466  2017-01-07 18:24:55
2          458  2017-01-07 18:25:18
3          458  2017-01-07 18:26:21
4          592  2017-01-07 19:09:59
...        ...                  ...
2998      1307  2018-01-04 10:48:28
2999      1230  2018-01-04 11:22:00
3000      1307  2018-01-04 13:13:44
3001      1307  2018-01-04 13:13:45
3002      1224  2018-01-04 14:10:04

[3003 rows x 2 columns]

In [133]:
fp = os.path.join('data', 'login_table.csv')
login = pd.read_csv(fp)
latest_login(login)#['Time']#.dtypes

Login Id      Time
0          466  18:24:07
1          466  18:24:55
2          458  18:25:18
3          458  18:26:21
4          592  19:09:59
...        ...       ...
2998      1307  10:48:28
2999      1230  11:22:00
3000      1307  13:13:44
3001      1307  13:13:45
3002      1224  14:10:04

[3003 rows x 2 columns]

In [128]:
login.dtypes

Login Id     int64
Time        object
Times       object
dtype: object

In [136]:
# don't change this cell -- it is needed for the tests to work
fp = os.path.join('data', 'login_table.csv')
login = pd.read_csv(fp)
q1_result = latest_login(login)

In [137]:
grader.check("q1")

q1 results: All test cases passed!

### Question 2 – Return Users 🔁

As a site owner, you would like to see how often users return to your site. You've noticed that there are users who have several logins and users who logged in only once. Of those users that logged in more than once, you are interested in finding the shortest amount of time elapsed between two consecutive logins for each of these users.

Write a function `smallest_elapsed` which takes in a DataFrame like `login` and outputs a DataFrame, indexed by `'Login ID'`, containing the shortest time elapsed for each user. Any users who haven't logged in more than once should not be included in the output. Your DataFrame should only have a single column, named `'Time'`.

***Hint:*** You need not do any querying for this question. There is a built-in `numpy`/`pandas` method that you can use to find the smallest elapsed time for each user.

In [178]:
login['Login Id'].nunique()

433

In [218]:
fp = os.path.join('data', 'login_table.csv')
login = pd.read_csv(fp)
more_1 = (login.groupby('Login Id').count() > 1)['Time'].values
more_1

more_1_index = login.groupby('Login Id').count().loc[more_1].index
len(more_1_index)

more_1_df = login.set_index('Login Id').loc[more_1_index].reset_index()#[more_1]
more_1_df['Times'] = pd.to_datetime(more_1_df['Time'])
times = pd.DataFrame(more_1_df.groupby('Login Id').Time.apply(np.array, dtype =np.datetime64))#.apply(find_min)
times['Time'] = times['Time'].apply(np.diff)
times['Time'] = times['Time'].apply(min)
times

Time
Login Id                
381      0 days 00:00:00
393      0 days 00:00:19
412      0 days 00:00:14
413      0 days 00:00:00
419      0 days 00:25:16
...                  ...
1291     0 days 23:05:49
1302     0 days 06:52:55
1304     0 days 22:14:43
1306     0 days 17:31:30
1307     0 days 00:00:01

[238 rows x 1 columns]

In [210]:
def find_min(listy):
    return np.diff(listy).min()

In [219]:
# don't change this cell -- it is needed for the tests to work
fp = os.path.join('data', 'login_table.csv')
login = pd.read_csv(fp)
q2_result = smallest_elapsed(login)

In [220]:
grader.check("q2")

q2 results: All test cases passed!

## Part 2: Pivot Tables

### Question 3 – Summarizing Sales 💰

Recall from [Lecture 8](https://dsc80.com/resources/lectures/lec08/lec08.html), a pivot table allows you to aggregate the entries in a DataFrame based on two categorical columns. In this question, you are given a simple dataset, `data/sales.csv`, and are asked to solve a few simple problems using the `pivot_table` method.  

We have provided the outline for your DataFrames, but yours may have a different number of rows and columns and different values.

#### `total_seller`

Write a function `total_seller` that takes in the `sales` DataFrame and returns a DataFrame that contains the total sales for each seller, indexed by `'Name'`. There should not be any `NaN`s.

***Note:*** You may be able to implement `total_seller` without using `pivot_table`.

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Total</th>
    </tr>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Jones</th>
      <td>0</td>
    </tr>
    <tr>
      <th>Smith</th>
      <td>0</td>
    </tr>
    <tr>
      <th>Trump</th>
      <td>0</td>
    </tr>
  </tbody>
</table>

<br>

#### `product_name`

Write a function `product_name` that takes in the `sales` DataFrame and returns a DataFrame that contains the total sales for each seller, indexed by `'Product'`. Do not fill in `NaN`s.

<table border="1" class="dataframe">
  <thead>
    <tr>
      <th>Name</th>
      <th>Jones</th>
      <th>Smith</th>
      <th>Trump</th>
    </tr>
    <tr>
      <th>Product</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>boat</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>book</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>hotel</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>pen</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>ruler</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

<br>

#### `count_product`

Write a function `count_product` that takes in the `sales` DataFrame and returns a DataFrame that contains the total number of items sold product-wise and name-wise per date. Replace `NaN`s with 0s. Don't reset the index after pivoting.

<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th>Date</th>
      <th>01.01.2012</th>
      <th>02.20.2013</th>
      <th>02.25.2015</th>
    </tr>
    <tr>
      <th>Product</th>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>boat</th>
      <th>Trump</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">book</th>
      <th>Jones</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>Smith</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>Trump</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>hotel</th>
      <th>Trump</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

<br>

#### `product_name`

Write a function `total_by_month` that takes in the `sales` DataFrame and returns a pivot table that contains the total sales name-wise, product-wise per month. Replace `NaN`s with 0s. Don't reset the index after pivoting.

<table border="1" class="dataframe">
  <thead>
    <tr>
      <th></th>
      <th>Month</th>
      <th>February</th>
      <th>January</th>
      <th>July</th>
      <th>March</th>
    </tr>
    <tr>
      <th>Name</th>
      <th>Product</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="3" valign="top">Jones</th>
      <th>book</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>pen</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>ruler</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">Smith</th>
      <th>book</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>pen</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>ruler</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

<br>


***Note:*** [Here](https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html) is another great resource that provides an overview of `pivot_table` with many examples from the Titanic dataset.

In [ ]:
df.pivot_table(index=index_col,
               columns=columns_col,
               values=values_col,
               aggfunc=func)

In [249]:
def get_month(dt):
    month = dt[0:2]
    if month ==  '01':
        return 'January'
    elif month == '02':
        return 'Feburary'
    elif month == '03':
        return 'March'
    elif month == '04':
        return 'April'
    elif month == '05':
        return 'May'
    elif month == '06':
        return 'June'
    elif month == '07':
        return 'July'
    elif month == '08':
        return 'August'
    elif month == '09':
        return 'September'
    elif month == '10':
        return 'October'
    elif month == '11':
        return 'November'
    else:
        return 'December'

In [241]:

sales

Name Product        Date  Total
0   Smith    book  01.01.2012    200
1   Jones     pen  02.20.2013    300
2   Trump   hotel  03.03.2015    100
3   Smith    book  05.10.2013   2000
4   Jones    book  02.20.2013     30
5   Trump    boat  03.30.2017    700
6   Smith   ruler  07.05.2014   2100
7   Jones   ruler  02.25.2015    350
8   Trump    book  03.03.2015   1000
9   Smith     pen  01.01.2012   2500
10  Jones   ruler  02.20.2013   3000
11  Trump     pen  03.03.2015    150

In [252]:
sales['Month']= sales['Date'].apply(get_month)
sales
out1 = sales.pivot_table(index = ['Name','Product'], columns = 'Month', values = 'Total', aggfunc = 'sum' ).fillna(0)
out1

Month          Feburary  January    July   March     May
Name  Product                                           
Jones book         30.0      0.0     0.0     0.0     0.0
      pen         300.0      0.0     0.0     0.0     0.0
      ruler      3350.0      0.0     0.0     0.0     0.0
Smith book          0.0    200.0     0.0     0.0  2000.0
      pen           0.0   2500.0     0.0     0.0     0.0
      ruler         0.0      0.0  2100.0     0.0     0.0
Trump boat          0.0      0.0     0.0   700.0     0.0
      book          0.0      0.0     0.0  1000.0     0.0
      hotel         0.0      0.0     0.0   100.0     0.0
      pen           0.0      0.0     0.0   150.0     0.0

In [ ]:
fp = os.path.join('data', 'sales.csv')
sales = pd.read_csv(fp)
out1 = sales.pivot_table(index = ['Product','Name'], columns = '', values = 'Product', aggfunc = 'count' ).fillna(0)


In [234]:
fp = os.path.join('data', 'sales.csv')
sales = pd.read_csv(fp)
out1 = sales.pivot_table(index = ['Name','Product'], columns = 'Month', values = 'Total', aggfunc = 'sum' ).fillna(0)
out1.size

KeyError: 'Month'

In [226]:
fp = os.path.join('data', 'sales.csv')
sales = pd.read_csv(fp)
sales.pivot_table(index = 'Product', columns = 'Name', values = 'Total', aggfunc = 'sum' )


Name      Jones   Smith   Trump
Product                        
boat        NaN     NaN   700.0
book       30.0  2200.0  1000.0
hotel       NaN     NaN   100.0
pen       300.0  2500.0   150.0
ruler    3350.0  2100.0     NaN

In [223]:
fp = os.path.join('data', 'sales.csv')
sales = pd.read_csv(fp)
sales.groupby('Name').sum()

Total
Name        
Jones   3680
Smith   6800
Trump   1950

In [253]:
# don't change this cell -- it is needed for the tests to work
fp = os.path.join('data', 'sales.csv')
sales = pd.read_csv(fp)
q3_total_seller_out = total_seller(sales)
q3_product_name_out = product_name(sales)
q3_product_count_out = count_product(sales)
q3_total_by_month_out = total_by_month(sales)

In [254]:
grader.check("q3")

q3 results: All test cases passed!

## Part 3: Permutation Testing

[Skittles](https://en.wikipedia.org/wiki/Skittles_(confectionery)) 🍬 are made in two locations in the United States: Yorkville, Illinois and Waco, Texas. In these factories, Skittles of different colors are made separately by different machines and combined/packaged into bags for sale. The **tab-separated file** `data/skittles.tsv` contains the contents of 468 bags of Skittles.

Throughout this question, we will compare the color distribution of Skittles between bags made in the Yorkville factory and bags made in the Waco factory. Most people have preferences for their favorite flavor and there is a surprising amount of variation among the distribution of flavors in each bag.

Look at the variation by bag in the dataset below:

In [276]:
skittles_fp = os.path.join('data', 'skittles.tsv')
skittles = pd.read_csv(skittles_fp, sep='\t')
skittles.head()

red  orange  yellow  green  purple    Factory
0   10      15      11      7      18  Yorkville
1    5      12      17     15      10  Yorkville
2   16      11      15     11       9       Waco
3   15       8      13     16       7       Waco
4   11      14      20      8       7       Waco

In [256]:
skittles.shape

(468, 6)

### Question 4 – Orange Skittles 🟠

First, you will investigate if the machine that mixes together the Skittles of different colors might favor one color over another. Use a permutation test to assess whether, on average, bags made in Yorkville have the same number of orange skittles as bags made in Waco. Do this by implementing the functions described below.

<br>

#### `diff_of_means`

Create a function `diff_of_means` that takes in a DataFrame like `skittles` and returns the **absolute difference** between the **mean** number of orange Skittles per bag from Yorkville and the **mean** number of orange Skittles per bag from Waco.

<br>

#### `simulate_null`

Create a function `simulate_null` that takes in a DataFrame like `skittles` and returns one simulated instance of the test statistic under the null hypothesis. Note that this will involve shuffling!

<br>

#### `pval_color`

Create a function `pval_color` that takes in a DataFrame like `skittles` and calculates the p-value for the permutation test using 1000 trials.

<br>

Plot the observed statistic, along with the histogram for the simulated distribution, to check your work.

***Note:*** In all functions, the default argument for `col` is `'orange'`. Your functions should still work for any color so that you can call it in later questions.

In [272]:
col = 'orange'
observed = diff_of_means(skittles, col)
observed


test_stats = np.array([])
for n in np.arange(1000):
    test_stat = simulate_null(skittles,col)
    
    test_stats = np.append(test_stats, test_stat)

(test_stats >= observed).mean()

0.054

In [265]:
shuffled_weights = (
    skittles['Factory']
    .sample(frac=1)
    .reset_index(drop=True)
)




shuffled = (
        skittles
        .assign(**{'Factory': shuffled_weights})
    )



red  orange  yellow  green  purple    Factory
0     10      15      11      7      18  Yorkville
1      5      12      17     15      10       Waco
2     16      11      15     11       9  Yorkville
3     15       8      13     16       7       Waco
4     11      14      20      8       7  Yorkville
..   ...     ...     ...    ...     ...        ...
463   11      11      12     13      11  Yorkville
464   17      10       8     11      12       Waco
465    9      14      12     10      15  Yorkville
466   12      14      11     10      10  Yorkville
467   11       8      12     13      15  Yorkville

[468 rows x 6 columns]

In [263]:
col = 'orange'
fact_means = skittles.groupby('Factory').mean()[col].values
np.abs(fact_means[0] - fact_means[1])

0.6004398826979482

In [258]:
skittles.head()

red  orange  yellow  green  purple    Factory
0   10      15      11      7      18  Yorkville
1    5      12      17     15      10  Yorkville
2   16      11      15     11       9       Waco
3   15       8      13     16       7       Waco
4   11      14      20      8       7       Waco

In [273]:
# don't change this cell -- it is needed for the tests to work
skittles_fp = os.path.join('data', 'skittles.tsv')
skittles = pd.read_csv(skittles_fp, sep='\\t', engine='python')
q4_diff_of_means_out = diff_of_means(skittles)
q4_simulate_null_out = simulate_null(skittles)
q4_many_diffs = np.array([simulate_null(skittles) for _ in range(100)])
q4_pval_out = pval_color(skittles)

In [274]:
grader.check("q4")

q4 results: All test cases passed!

### Question 5 – Generalizing to all colors 🔴🟠🟡🟢🟣

While your `pval_color` function used a default color of `'orange'`, it should also work for all other colors of Skittles, meaning you can run the same permutation test from Question 4 on all colors of Skittles. Call `pval_color` on all colors of Skittles to find which colors differ the most between the two locations on average. 

Then, create a function `ordered_colors` that returns a list of five ordered pairs, each of the form `('color', p_value)`. For example, your list might look like `[('pink', 0.000), ('brown', 0.025), ...]`. 

The list should be **hard-coded**, meaning that you should run your permutation tests in your notebook, not in your `.py` file. The list should also be sorted in **increasing order of p-value**. Make sure your p-values are rounded to **3 decimal places**.

Even though there is randomness in the color composition in each bag, this list gives the likelihood that the machines have a systematic, meaningful, difference in how they blend the colors in each bag.

In [316]:
skittles

red  orange  yellow  green  purple    Factory
0     10      15      11      7      18  Yorkville
1      5      12      17     15      10  Yorkville
2     16      11      15     11       9       Waco
3     15       8      13     16       7       Waco
4     11      14      20      8       7       Waco
..   ...     ...     ...    ...     ...        ...
463   11      11      12     13      11       Waco
464   17      10       8     11      12       Waco
465    9      14      12     10      15       Waco
466   12      14      11     10      10       Waco
467   11       8      12     13      15  Yorkville

[468 rows x 6 columns]

In [278]:
print(pval_color(skittles, 'red'))
print(pval_color(skittles, 'orange'))
print(pval_color(skittles, 'yellow'))
print(pval_color(skittles, 'green'))
print(pval_color(skittles, 'purple'))

0.241
0.043
0.0
0.494
0.985


In [279]:
# don't change this cell -- it is needed for the tests to work
q5_out = ordered_colors()
q5_colors = {'green', 'orange', 'purple', 'red', 'yellow'}
q5_test_colors = [x[0] for x in q5_out]

In [280]:
grader.check("q5")

q5 results: All test cases passed!

### Question 6 – Overall distributions 🏭

Now, suppose you would like to assess whether the two locations make similar amounts of each color overall. That is, suppose we:
* Combine and count up all the Skittles of each color that were made in Yorkville (e.g. 14303 total red skittles, 9091 total green skittles, etc.)
* Combine and count up all the Skittles of each color that were made in Waco.

**Are these distributions of colors similar?** Is the variation among the bags due to each factory making different amounts of each color?

Use a permutation test to assess whether the distribution of colors of Skittles made in Yorkville is statistically significantly different than those made in Waco. Set a significance level of 0.01 and determine whether you can reject a null hypothesis that answers the question above using a permutation test with 1000 trials. For your test statistic, use the **total variation distance (TVD)**.

Refer to [Lecture 10](https://dsc80.com/resources/lectures/lec10/lec10.html) to see an example of a [permutation test](https://www.inferentialthinking.com/chapters/12/Comparing_Two_Samples.html) that uses the [TVD](https://inferentialthinking.com/chapters/11/2/Multiple_Categories.html) as the test statistic. Some guidance:

- Our previous permutation tests have compared the mean number of (say) orange Skittles in Yorkville bags to the mean number of orange Skittles in Waco bags. The role of shuffling was to randomly assign bags to Yorkville and Waco.
- In this permutation test, we are **still** shuffling to randomly assign bags to Yorkville and Waco. The only difference is that after we randomly assign each bag to a factory, we will compute the distribution of colors amongst the two factories and find the TVD between those two distributions.

**Your job:** Create a function `same_color_distribution` that takes in no arguments and outputs a hard-coded **tuple** with the p-value and whether you `'Fail to Reject'` or `'Reject'` the null hypothesis.

In [376]:
def tvd(data):
    fact_means = data.groupby('Factory').sum().values
    print(fact_means[0])
    print(fact_means[1])
    print()
    print((np.abs((fact_means[0]/ fact_means[0].sum()) - (fact_means[1]/fact_means[1].sum()))))
    print((np.abs((fact_means[0]/ fact_means[0].sum()) - (fact_means[1]) / fact_means[1].sum())).sum() / 2)
    return (np.abs((fact_means[0]/ fact_means[0].sum()) - (fact_means[1]) / fact_means[1].sum())).sum() / 2

In [379]:
observed_tvd = tvd(skittles)
#observed
print(observed_tvd)

test_stats = np.array([])

for n in np.arange(1000):
    
    shuffled_weights = (
    skittles['Factory']
    .sample(frac=1)
    .reset_index(drop=True)
    )


    shuffled = (
        skittles
        .assign(**{'Factory': shuffled_weights})
    )

    #print(shuffled['orange'])
    test_stat = tvd(shuffled)
    
    test_stats = np.append(test_stats, test_stat)

(test_stats >= observed_tvd).mean() 

#test_stats






#np.abs(fact_means[0] - fact_means[1])

[2666 2655 2532 2517 2666]
[2917 2844 3156 2784 3003]

[0.00612919 0.01025001 0.02040411 0.00374446 0.00028044]
0.020404114027914977
0.020404114027914977
[2666 2521 2684 2495 2641]
[2917 2978 3004 2806 3028]

[0.00697565 0.00831256 0.00245441 0.00136299 0.0024805 ]
0.01079305432344227
[2603 2575 2759 2479 2635]
[2980 2924 2929 2822 3034]

[0.00342458 0.00175763 0.01200051 0.00216942 0.00464888]
0.0120005129308874
[2645 2544 2728 2518 2645]
[2938 2955 2960 2783 3024]

[0.00180785 0.00707348 0.00665273 0.00267136 0.00405845]
0.011131936534955408
[2605 2576 2666 2454 2723]
[2978 2923 3022 2847 2946]

[0.00234942 0.00083865 0.0006557  0.00504152 0.00888528]
0.008885283730690086
[2630 2582 2655 2513 2679]
[2953 2917 3033 2788 2990]

[0.00024934 0.00097414 0.00328549 0.00252902 0.00148128]
0.004259631218220469
[2641 2571 2679 2509 2671]
[2942 2928 3009 2792 2998]

[1.49133847e-03 2.90963475e-03 1.68917563e-04 1.61829263e-03
 3.10787872e-05]
0.0031096311023066786
[2624 2640 2673 2497 2642]
[2

[2663 2603 2633 2473 2662]
[2920 2896 3055 2828 3007]

[0.00575339 0.00278203 0.00572821 0.00256792 0.00023929]
0.008535418597117705
[2614 2566 2660 2481 2700]
[2969 2933 3028 2820 2969]

[0.00095944 0.00219998 0.00143511 0.00105074 0.00564527]
0.005645272994938694
[2624 2586 2653 2492 2673]
[2959 2913 3035 2809 2996]

[0.00028401 0.00049392 0.00265586 0.00034775 0.00153019]
0.0026558641503814095
[2615 2573 2683 2484 2660]
[2968 2926 3005 2817 3009]

[6.39956378e-04 1.01471007e-03 2.07205086e-03 4.50596706e-04
 3.32122985e-05]
0.002105263157894735
[2662 2563 2668 2528 2653]
[2921 2936 3020 2773 3016]

[0.00444207 0.00415298 0.00184931 0.00428409 0.00272388]
0.008726167431241036
[2610 2570 2674 2477 2695]
[2973 2929 3014 2824 2974]

[0.00168397 0.00176441 0.00044282 0.00176791 0.00477347]
0.005216290268450441
[2582 2596 2664 2449 2733]
[3001 2903 3024 2852 2936]

[0.00567831 0.00205604 0.00094517 0.00576519 0.01033263]
0.012388674380723844
[2599 2590 2722 2448 2673]
[2984 2909 2966 2853

[2589 2582 2676 2500 2664]
[2994 2917 3012 2801 3005]

[0.00428698 0.00040279 0.00117759 0.00197605 0.00073055]
0.004286981869803877
[2639 2568 2691 2480 2666]
[2944 2931 2997 2821 3003]

[1.98862124e-03 2.56989993e-03 2.36870493e-03 1.83126680e-03
 4.38405617e-05]
0.004401166722338562
[2596 2641 2690 2455 2629]
[2987 2858 2998 2846 3040]

[0.00327372 0.00894312 0.00320411 0.00453776 0.00433575]
0.012147228743641172
[2569 2581 2692 2539 2643]
[3014 2918 2996 2762 3026]

[0.00755986 0.00011497 0.0031074  0.00726092 0.00269348]
0.010368317457540063
[2681 2570 2703 2432 2634]
[2902 2929 2985 2869 3035]

[0.00876724 0.00159235 0.00481836 0.00811534 0.00387792]
0.013585599913177052
[2591 2569 2643 2539 2692]
[2992 2930 3045 2762 2977]

[0.00466659 0.00213851 0.00428099 0.00698372 0.00410237]
0.011086092069280934
[2622 2575 2685 2569 2588]
[2961 2924 3003 2732 3081]

[0.00032583 0.00141356 0.00164888 0.01118661 0.0110961 ]
0.012835494761053362
[2633 2554 2660 2537 2658]
[2950 2945 3028 2764 

[2600 2633 2717 2490 2634]
[2983 2866 2971 2811 3035]

[0.00452763 0.0059741  0.00523965 0.00121347 0.00547266]
0.011213753906499313
[2662 2563 2702 2472 2656]
[2921 2936 2986 2829 3013]

[0.0049961  0.00360866 0.00363377 0.00329282 0.00172839]
0.00862986758700228
[2610 2597 2740 2464 2640]
[2973 2902 2948 2837 3029]

[0.00241168 0.00142578 0.0092512  0.00433993 0.00392538]
0.010676982024034193
[2604 2597 2743 2423 2667]
[2979 2902 2945 2878 3002]

[0.0027852  0.0019137  0.0101912  0.00980401 0.00048432]
0.012589217070519992
[2607 2550 2675 2558 2628]
[2976 2949 3013 2743 3041]

[0.00188527 0.00442983 0.00082502 0.01017736 0.00468728]
0.011002384772370283
[2579 2616 2650 2527 2650]
[3004 2883 3038 2774 3019]

[0.00605436 0.00500821 0.00291215 0.00557952 0.00162121]
0.010587724800925916
[2670 2578 2687 2454 2614]
[2913 2921 3001 2847 3055]

[7.67149057e-03 5.33489302e-05 3.00751658e-03 4.46153716e-03
 6.27081893e-03]
0.010732356088573342
[2617 2564 2632 2519 2673]
[2966 2935 3056 2782 2

[2660 2543 2697 2509 2629]
[2923 2956 2991 2792 3040]

[0.00520253 0.00601583 0.00341517 0.00253136 0.00513323]
0.011149060240997016
[2602 2536 2669 2581 2656]
[2981 2963 3019 2720 3013]

[0.00336562 0.0072006  0.0008149  0.01278438 0.00140325]
0.012784375215446842
[2672 2508 2659 2460 2734]
[2911 2991 3029 2841 2935]

[0.00708507 0.01093795 0.00193578 0.00442169 0.01021035]
0.017295427049884432
[2580 2509 2756 2544 2648]
[3003 2990 2932 2757 3021]

[0.00634574 0.01090761 0.01198324 0.00762417 0.00235406]
0.019607407982546787
[2611 2591 2642 2524 2652]
[2972 2908 3046 2777 3017]

[0.00136454 0.00144719 0.00401076 0.00520072 0.0012726 ]
0.006647903726708065
[2588 2624 2658 2446 2737]
[2995 2875 3030 2855 2932]

[0.00565324 0.00527524 0.00267355 0.00699972 0.01005127]
0.01532650893179155
[2632 2590 2644 2491 2656]
[2951 2909 3044 2810 3013]

[0.00187903 0.00150339 0.00351375 0.00061796 0.00048662]
0.004000371504328151
[2662 2599 2671 2494 2614]
[2921 2900 3017 2807 3055]

[0.00543362 0.0

[2666 2550 2650 2519 2679]
[2917 2949 3038 2782 2990]

[0.00531238 0.00574741 0.00415711 0.00325877 0.00133337]
0.009904527714952427
[2663 2570 2720 2502 2588]
[2920 2929 2968 2799 3081]

[0.00549082 0.00225181 0.006595   0.00138    0.01121401]
0.013465824993656117
[2662 2605 2614 2459 2689]
[2921 2894 3074 2842 2980]

[0.00575455 0.00321506 0.00832992 0.00445594 0.00381625]
0.012785860444580952
[2632 2583 2703 2466 2645]
[2951 2916 2985 2835 3024]

[1.41270694e-03 3.10377828e-05 4.55089338e-03 3.44284610e-03
 2.55179200e-03]
0.005994638096505023
[2561 2633 2726 2447 2682]
[3022 2866 2962 2854 2987]

[0.00944392 0.00669249 0.00728486 0.00674465 0.00221123]
0.01618857442287805
[2668 2605 2699 2400 2691]
[2915 2894 2989 2901 2978]

[0.00563092 0.00223894 0.00296213 0.01393117 0.00309918]
0.013931171891026717
[2727 2603 2632 2450 2655]
[2856 2896 3056 2851 3014]

[0.01405043 0.00183478 0.00685027 0.00680724 0.00222771]
0.0158852176707341
[2627 2592 2643 2498 2719]
[2956 2907 3045 2803 295

[2590 2568 2679 2499 2697]
[2993 2931 3009 2802 2972]

[0.00478222 0.00225457 0.00095868 0.00122251 0.0048556 ]
0.007036789534540913
[2638 2605 2659 2452 2646]
[2945 2894 3029 2849 3023]

[0.0031266  0.00404812 0.00095679 0.0046682  0.00154973]
0.007174720801586459
[2586 2616 2662 2447 2704]
[2997 2883 3026 2854 2965]

[0.00483759 0.00520937 0.00096762 0.0058062  0.00640204]
0.011611416107964762
[2632 2632 2715 2426 2666]
[2951 2867 2973 2875 3003]

[0.00018925 0.00591561 0.00503943 0.01038983 0.00075446]
0.011144292936182826
[2574 2561 2730 2518 2635]
[3009 2938 2958 2783 3034]

[0.00666177 0.00283767 0.00878585 0.00438767 0.00367408]
0.013173518806028017
[2654 2585 2721 2444 2595]
[2929 2914 2967 2857 3074]

[0.00547204 0.00118151 0.00804844 0.00579871 0.00890328]
0.014701991421391614
[2598 2611 2680 2500 2643]
[2985 2888 3008 2801 3026]

[0.00359534 0.00399725 0.00113309 0.00139491 0.0029299 ]
0.006525244526850757
[2636 2598 2621 2541 2622]
[2947 2901 3067 2760 3047]

[0.00231226 0.

[2642 2542 2669 2513 2669]
[2941 2957 3019 2788 3000]

[0.00268508 0.00607464 0.00054789 0.00319327 0.00074418]
0.006622533140250783
[2632 2607 2619 2494 2701]
[2951 2892 3069 2807 2968]

[7.13480884e-04 2.81537039e-03 8.31677481e-03 5.42122577e-05
 4.84213579e-03]
0.008370987066461763
[2586 2613 2661 2461 2708]
[2997 2886 3027 2840 2961]

[0.00524479 0.00437288 0.00152769 0.00416649 0.00656608]
0.01093896889313481
[2687 2581 2694 2440 2616]
[2896 2918 2994 2861 3053]

[9.69411085e-03 5.71768487e-05 3.57512361e-03 6.90222346e-03
 6.42418785e-03]
0.013326411306518862
[2660 2499 2666 2556 2649]
[2923 3000 3022 2745 3020]

[0.00543592 0.01215471 0.00083372 0.00955495 0.00200244]
0.014990872394562982
[2565 2633 2684 2473 2653]
[3018 2866 3004 2828 3016]

[0.00767382 0.00787141 0.00242471 0.0018493  0.00077299]
0.010296113855789657
[2651 2632 2684 2450 2646]
[2932 2867 3004 2851 3023]

[0.00317126 0.00614546 0.00079184 0.00669688 0.00341168]
0.010108558713408669
[2578 2573 2752 2463 2625]
[

[2661 2542 2657 2493 2672]
[2922 2957 3031 2808 2997]

[0.00572654 0.00578826 0.00198797 0.00057546 0.00147423]
0.007776232095026217
[2641 2597 2684 2410 2721]
[2942 2902 3004 2891 2948]

[0.00201576 0.00136839 0.00108861 0.01220886 0.0077361 ]
0.01220885812434111
[2604 2597 2677 2463 2677]
[2979 2902 3011 2838 2992]

[0.0023195  0.00237305 0.00111451 0.00357315 0.00240509]
0.005892648739482684
[2645 2616 2657 2484 2650]
[2938 2883 3031 2817 3019]

[0.0026237  0.00414637 0.0027886  0.00147356 0.00250792]
0.006770074887311822
[2627 2553 2630 2580 2653]
[2956 2946 3058 2721 3016]

[0.00028124 0.00471189 0.00642895 0.01266743 0.00180782]
0.012948664664391901
[2584 2583 2676 2499 2693]
[2999 2916 3012 2802 2976]

[0.00570872 0.00014109 0.00046515 0.00116718 0.00421748]
0.005849811671477426
[2688 2555 2701 2484 2622]
[2895 2944 2987 2817 3047]

[0.00890417 0.004623   0.00363758 0.00141828 0.00650047]
0.012541750454475503
[2609 2663 2686 2443 2621]
[2974 2836 3002 2858 3048]

[0.00171225 0.0

[2596 2603 2634 2516 2693]
[2987 2896 3054 2785 2976]

[0.0041757  0.00255234 0.00582048 0.00343363 0.00401021]
0.009996185742707303
[2605 2606 2606 2518 2704]
[2978 2893 3082 2783 2965]

[0.00278599 0.00307262 0.00978365 0.00380612 0.00569091]
0.01256964378666546
[2589 2607 2764 2518 2562]
[2994 2892 2924 2783 3107]

[0.00513052 0.00318862 0.01305163 0.00377843 0.01488815]
0.020018676182129297
[2613 2586 2686 2468 2668]
[2970 2913 3002 2833 3001]

[0.00110418 0.00069479 0.00232809 0.00293234 0.00101364]
0.004036521686690497
[2614 2607 2686 2511 2621]
[2969 2892 3002 2790 3048]

[0.00148355 0.00321733 0.0017936  0.00279311 0.00632049]
0.0078040407459605
[2625 2549 2705 2506 2642]
[2958 2950 2983 2795 3027]

[0.00045787 0.00483243 0.00489979 0.00240164 0.00292687]
0.007759300305821698
[2688 2537 2659 2462 2693]
[2895 2962 3029 2839 2976]

[0.0092254  0.00691276 0.00211372 0.00429795 0.00409903]
0.01332443414238299
[2617 2621 2672 2420 2676]
[2966 2878 3016 2881 2993]

[8.82845292e-05 6.

[2610 2629 2681 2495 2597]
[2973 2870 3007 2806 3072]

[0.00127633 0.00717735 0.00187165 0.00122462 0.00899729]
0.010273619487664656
[2600 2587 2642 2512 2704]
[2983 2912 3046 2789 2965]

[0.00368414 0.00015089 0.00475168 0.00277175 0.00551317]
0.008435818588545863
[2630 2590 2672 2512 2657]
[2953 2909 3016 2789 3012]

[0.00019109 0.00012602 0.00088507 0.00232899 0.00176103]
0.0026461016017119976
[2640 2627 2640 2474 2663]
[2943 2872 3048 2827 3006]

[0.00213333 0.00596795 0.00501147 0.00269952 0.00039029]
0.00810128092063761
[2671 2576 2674 2456 2651]
[2912 2923 3014 2845 3018]

[0.0070863  0.00095338 0.00038345 0.00486251 0.00165386]
0.007469752269884111
[2602 2625 2714 2447 2666]
[2981 2874 2974 2854 3003]

[0.00365656 0.00539121 0.00539983 0.00688262 0.00025187]
0.010791042377297805
[2606 2600 2642 2487 2704]
[2977 2899 3046 2814 2965]

[0.00264128 0.00220433 0.00457389 0.00068006 0.00569091]
0.007895231386311777
[2604 2604 2608 2529 2664]
[2979 2895 3080 2772 3005]

[0.00205748 0.

0.006

In [364]:
sums = skittles.groupby('Factory').sum().values
(np.abs(sums[0] - sums[1]).sum()) / 2

834.0

In [378]:
observed_tvd = tvd(skittles)
observed_tvd

[2666 2655 2532 2517 2666]
[2917 2844 3156 2784 3003]

[0.00612919 0.01025001 0.02040411 0.00374446 0.00028044]
0.020404114027914977


0.020404114027914977

In [380]:
# don't change this cell -- it is needed for the tests to work
q6_out = same_color_distribution()

In [381]:
grader.check("q6")

q6 results: All test cases passed!

### Question 7 – Permutation testing vs. hypothesis testing 🧪

In each of the following scenarios, decide  whether  a  permutation test is appropriate to determine if there is a  significant difference between the quantities described. If a permutation test is appropriate, mark `'P'`. Otherwise, mark `'H'`.

Record your answers in the function `perm_vs_hyp` that outputs a list of length 5, containing the values `'P'` and `'H'`.

1. Compare the DSC 80 pass rate between second years and third years who take the class.
2. Compare the proportion of Data Science majors who have completed DSC 80 and the proportion of Data Science minors who have completed DSC 80.
3. Compare the proportion of students who have iPhones to the proportion of students who have Android phones (for simplicity, assume that all students either have an iPhone or an Android).
4. In DSC 80, we ask all students whether they liked DSC 40A or DSC 40B more. Compare the proportion of students who preferred DSC 40A to the proportion who preferred DSC 40B.
5. Compare the attendance rate of classes that play music before class vs. classes that do not play music before class.

***Hint:*** Think about the type of data you would collect in each case, and how you would simulate new data under the null hypothesis.

In [384]:
# don't change this cell -- it is needed for the tests to work
q7_out = perm_vs_hyp()

In [385]:
grader.check("q7")

q7 results: All test cases passed!

## Part 4: Types of Missingness

First, let's recap the different mechanisms of missingness we studied in lecture.

### Missing by Design (MD)
- The missing field is deliberately missing. The missing field is deliberately set to null or not collected (hence, "missing by design").
- The missingness can be exactly predicted when a column will be null, with only knowledge of the other columns using a function of the rows of the dataset.

### Missing Completely at Random (MCAR)
- The missingness of missing value isn't related to the actual, unreported value itself, nor the values in any other fields. The missingness is not systematic.
- The missingness is unconditionally uniform across rows. MCAR doesn't bias the observed data.
- There is no relationship between the missing data and the any of the other data, observed or missing.

### Missing at Random (MAR)
- The missingness of the missing value has nothing to do with the value itself, but may be related to another field.
- The missingness is uniform across rows, perhaps conditional on another column. MAR biases the observed data, but is fixable.
- There is a systematic relationship between the missing values and the observed data (but not the missing values themselves).
- Difference between MD and MAR: If you can *exactly/always* determine missingness using the other columns, the missingness is MD. If there is just some sort of systematic relationship between the missing columns/values and other columns/values that may help us predict missingness, the missingness is MAR.

### Non-Ignorable (NI, aka NMAR)
- The missingness of the missing value is related to the actual, unreported value.
- NI biases the observed data in unobservable ways.
- There is relationship between the propensity of a value to be missing and its value.
- ***Note:*** In lecture, we referred to non-ignorable missingness as "not missing at random (NMAR)".

### Question 8 – After-purchase surveys 🛒

You run a small e-commerce website and send surveys out to customers after they purchase an item from your store. The survey asks whether the customer is satisfied with their purchase ("Yes" or "No"). Below, you are presented with possible datasets, each of which contains a column `'satisfied'` as described above, as well as a `'customer_id'` number corresponding to the customer and an `'item'` column describing the item that the customer purchased. **The column `'satisfied'` is missing data.**

For each of the following datasets, label the column `'satisfied'` as being `'MD'`, `'MCAR'`, `'MAR'`, or `'NI'`.

1. The dataset consists only of the columns `'customer_id'` and `'satisfied'`.
2. The dataset contains the `'customer_id'` of every customer with an account, even if they didn't make a purchase. Also, in this case, you notice everyone who was sent a survey filled it out.
3. The dataset contains a column specifying if the user later returned the item.
4. The dataset contains a column with the serial number for the item purchased.
5. The dataset contains a column with the price of the item purchased.

Record your answers in the function `after_purchase` that outputs a list of length 5, containing the values `'MD'`, `'MCAR'`, `'MAR'`, or `'NI'`. For some questions there may be multiple good answers, but there is generally one answer that is "best". If you are unsure, ask a tutor, but be prepared to provide justification for whichever answer(s) you think might be right.

***Disclaimer:*** We know that this lab has no hidden tests, and so it is possible to just look at the correct answers by running `grader.check`. This is not a good idea – you should really think about all of the questions here, since similar questions will be on the Midterm Exam.

In [390]:
# don't change this cell -- it is needed for the tests to work
q8_out = after_purchase()

In [391]:
grader.check("q8")

q8 results: All test cases passed!

### Question 9 – Miscellaneous missingness questions 🕵️

In each of the following scenarios, choose the best answer out of the missingness types: `'MD'`, `'MCAR'`, `'MAR'`, and `'NI'`. Store your answers in a list of length 5, and have the function `multiple_choice` return that list.

1. UCSD has recently adopted GrubHub as the food pre-ordering app for campus restaurants, so you can order your food ahead of time and stop by before your next class. In a DataFrame of GrubHub app orders, which contains information such as `'restaurant'`, `'name'`, `'items'`, and `'total'`, the column `'delivery_address'` is often missing for UCSD students. Which is the most likely missingness mechanism for this column?


2. In a database of student records that records student profile data, such as `'name'`, `'home_address'`, `'ethnicity'`, etc., sometimes the `'middle_name'` column is missing. Which is the most likely missingness mechanism for this column?


3. The UCSD Club Basketball team creates a signup sheet for potential new members. The sheet contains the columns `'full_name'`, `'year'`, `'email'`, `'favorite_sports'`, `'number_of_sports_played'`, and `'sports_previously_played'`. The team president notices that many students left the `'sports_previously_played'` column blank. Which is the most likely missingness mechanism for this column?


4. After the 2022 Sun God Festival, Associated Students sends out a survey to all students about whether their expectations for the 2022 Sun God Festival were met, with all questions being optional. They notice that many students left the "Were you satisfied with the 2022 Sun God Festival?" question blank. Which is the most likely missingness mechanism for answers to this question?


5. UCSD has been using a two-factor authentication system, DUO, since October 16th, 2019. When using DUO, all UCSD accounts are assigned a unique code. UCSD's Service Desk, who maintains DUO, has a database that stores each user's code and their phone number, which users must provide when they sign up for DUO. They notice that many phone numbers are missing. Which is the most likely missingness mechanism for phone numbers?

In [395]:
# don't change this cell -- it is needed for the tests to work
q9_out = multiple_choice()

In [396]:
grader.check("q9")

q9 results: All test cases passed!

## Congratulations! You're done! 🏁

Submit your `lab.py` file to Gradescope. Note that you only need to submit the `lab.py` file; this notebook should not be uploaded.

Before submitting, you should ensure that all of your work is in the `lab.py` file. You can do this by running the doctests below, which will verify that your work passes the public tests **and** that your work is in the `lab.py` file. Run the cell below; you should see no output.

In [397]:
!python -m doctest lab.py

**********************************************************************
File "/home/v/Documents/github_repos/dsc80-2022-sp/labs/04-pivot-perm-missing/lab.py", line 296, in lab.same_color_distribution
Failed example:
    isinstance(out, tuple)
Expected nothing
Got:
    False
**********************************************************************
1 items had failures:
   1 of   4 in lab.same_color_distribution
***Test Failed*** 1 failures.


In addition, `grader.check_all()` will verify that your work passes the public tests.

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [398]:
grader.check_all()

q1 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!

q4 results: All test cases passed!

q5 results: All test cases passed!

q6 results: All test cases passed!

q7 results: All test cases passed!

q8 results: All test cases passed!

q9 results: All test cases passed!